# Generated by Django 4.0.1 on 2024-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
