# Generated by Django 4.0.1 on 2024-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_joblisting_job_type_joblisting_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='job_type',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
