# Generated by Django 4.0.1 on 2024-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_joblisting_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(blank=True, choices=[('Software engineer', 'Software engineer'), ('Network administrator', 'Network administrator'), ('Web developer', 'Web developer'), ('Data architect', 'Data architect'), ('UX and UI designers', 'UX and UI designers'), ('Computer programmer', 'Computer programmer')], max_length=100, null=True),
        ),
    ]
