# Generated by Django 4.0.1 on 2024-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_joblisting_job_type_alter_joblisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
