# Generated by Django 4.0.1 on 2024-04-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
