# Generated by Django 4.0.1 on 2024-04-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_delete_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
