# Generated by Django 4.0.1 on 2024-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('seeker', 'Job Seeker'), ('admin', 'Administrator')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
