# Generated by Django 4.0.1 on 2024-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userregistration_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
